/**
 * Report Generator Tests
 * Tests for report generation functionality
 * 
 * Requirements: 26.5, 26.6, 26.7, 26.8
 */

import { describe, it, expect, beforeEach, vi } from 'vitest';
import {
  formatReportMetadata,
  formatCellValue,
  generateReportHTML,
  generateReportCSV,
  createPrintDocument,
  downloadReport,
  printReport,
  generateReportFilename,
  ReportData,
  ReportColumn,
  ReportMetadata,
} from '../reportGenerator';

describe('Report Generator', () => {
  let mockMetadata: ReportMetadata;
  let mockColumns: ReportColumn[];
  let mockData: ReportData;

  beforeEach(() => {
    mockMetadata = {
      title: 'Employee Report',
      description: 'Monthly employee attendance report',
      generatedDate: new Date('2024-01-15T10:00:00'),
      generatedBy: 'admin@example.com',
      filters: {
        department: 'Engineering',
        status: 'Active',
      },
      pageSize: 'A4',
    };

    mockColumns = [
      { id: 'name', label: 'Employee Name', align: 'left' },
      { id: 'department', label: 'Department', align: 'left' },
      { id: 'attendance', label: 'Attendance %', align: 'right', format: (v) => `${v}%` },
      { id: 'date', label: 'Date', align: 'center', format: (v) => new Date(v).toLocaleDateString() },
    ];

    mockData = {
      metadata: mockMetadata,
      columns: mockColumns,
      rows: [
        { name: 'John Doe', department: 'Engineering', attendance: 95, date: '2024-01-15' },
        { name: 'Jane Smith', department: 'Engineering', attendance: 98, date: '2024-01-15' },
        { name: 'Bob Johnson', department: 'Engineering', attendance: 92, date: '2024-01-15' },
      ],
      summary: [
        { label: 'Total Employees', value: 3 },
        { label: 'Average Attendance', value: '95%' },
      ],
    };
  });

  describe('formatReportMetadata', () => {
    it('should format metadata with all fields', () => {
      const result = formatReportMetadata(mockMetadata);

      expect(result).toContain('Generated:');
      expect(result).toContain('Generated By: admin@example.com');
      expect(result).toContain('Filters: department: Engineering');
      expect(result).toContain('status: Active');
    });

    it('should handle metadata without filters', () => {
      const metadata = { ...mockMetadata, filters: undefined };
      const result = formatReportMetadata(metadata);

      expect(result).toContain('Generated:');
      expect(result).toContain('Generated By:');
      expect(result).not.toContain('Filters:');
    });

    it('should handle metadata with empty filters', () => {
      const metadata = { ...mockMetadata, filters: {} };
      const result = formatReportMetadata(metadata);

      expect(result).not.toContain('Filters:');
    });

    it('should handle null/undefined filter values', () => {
      const metadata = {
        ...mockMetadata,
        filters: { department: 'Engineering', status: null, role: undefined },
      };
      const result = formatReportMetadata(metadata);

      expect(result).toContain('department: Engineering');
      expect(result).not.toContain('status:');
      expect(result).not.toContain('role:');
    });
  });

  describe('formatCellValue', () => {
    it('should format value using column format function', () => {
      const column: ReportColumn = {
        id: 'attendance',
        label: 'Attendance',
        format: (v) => `${v}%`,
      };
      const result = formatCellValue(95, column);

      expect(result).toBe('95%');
    });

    it('should format date values', () => {
      const column: ReportColumn = { id: 'date', label: 'Date' };
      const date = new Date('2024-01-15');
      const result = formatCellValue(date, column);

      expect(result).toBe(date.toLocaleDateString());
    });

    it('should format number values with locale', () => {
      const column: ReportColumn = { id: 'salary', label: 'Salary' };
      const result = formatCellValue(50000, column);

      expect(result).toBe('50,000');
    });

    it('should return dash for null/undefined values', () => {
      const column: ReportColumn = { id: 'notes', label: 'Notes' };

      expect(formatCellValue(null, column)).toBe('-');
      expect(formatCellValue(undefined, column)).toBe('-');
    });

    it('should convert string values', () => {
      const column: ReportColumn = { id: 'name', label: 'Name' };
      const result = formatCellValue('John Doe', column);

      expect(result).toBe('John Doe');
    });
  });

  describe('generateReportHTML', () => {
    it('should generate valid HTML structure', () => {
      const html = generateReportHTML(mockData);

      expect(html).toContain('<div class="report-container">');
      expect(html).toContain('<div class="report-header">');
      expect(html).toContain('<h1>Employee Report</h1>');
      expect(html).toContain('<div class="report-content">');
      expect(html).toContain('<table class="report-table">');
      expect(html).toContain('</table>');
      expect(html).toContain('</div>');
    });

    it('should include report title and description', () => {
      const html = generateReportHTML(mockData);

      expect(html).toContain('Employee Report');
      expect(html).toContain('Monthly employee attendance report');
    });

    it('should include metadata information', () => {
      const html = generateReportHTML(mockData);

      expect(html).toContain('Generated:');
      expect(html).toContain('Generated By:');
      expect(html).toContain('admin@example.com');
    });

    it('should include table headers', () => {
      const html = generateReportHTML(mockData);

      expect(html).toContain('<thead>');
      expect(html).toContain('Employee Name');
      expect(html).toContain('Department');
      expect(html).toContain('Attendance %');
    });

    it('should include table data rows', () => {
      const html = generateReportHTML(mockData);

      expect(html).toContain('John Doe');
      expect(html).toContain('Jane Smith');
      expect(html).toContain('Bob Johnson');
      expect(html).toContain('Engineering');
    });

    it('should include summary rows', () => {
      const html = generateReportHTML(mockData);

      expect(html).toContain('Total Employees');
      expect(html).toContain('Average Attendance');
      expect(html).toContain('95%');
    });

    it('should apply column alignment styles', () => {
      const html = generateReportHTML(mockData);

      expect(html).toContain('text-align: right');
      expect(html).toContain('text-align: center');
    });

    it('should handle data without summary', () => {
      const dataWithoutSummary = { ...mockData, summary: undefined };
      const html = generateReportHTML(dataWithoutSummary);

      expect(html).toContain('<table class="report-table">');
      expect(html).not.toContain('summary-row');
    });
  });

  describe('generateReportCSV', () => {
    it('should generate valid CSV format', () => {
      const csv = generateReportCSV(mockData);

      expect(csv).toContain('# Employee Report');
      expect(csv).toContain('# Monthly employee attendance report');
      expect(csv).toContain('"Employee Name","Department","Attendance %","Date"');
    });

    it('should include metadata as comments', () => {
      const csv = generateReportCSV(mockData);

      expect(csv).toContain('# Generated:');
      expect(csv).toContain('# Generated By: admin@example.com');
      expect(csv).toContain('# Filters:');
    });

    it('should include all data rows', () => {
      const csv = generateReportCSV(mockData);

      expect(csv).toContain('John Doe');
      expect(csv).toContain('Jane Smith');
      expect(csv).toContain('Bob Johnson');
    });

    it('should include summary section', () => {
      const csv = generateReportCSV(mockData);

      expect(csv).toContain('Total Employees');
      expect(csv).toContain('Average Attendance');
    });

    it('should escape quotes in values', () => {
      const dataWithQuotes = {
        ...mockData,
        rows: [{ name: 'John "Johnny" Doe', department: 'Engineering', attendance: 95, date: '2024-01-15' }],
      };
      const csv = generateReportCSV(dataWithQuotes);

      expect(csv).toContain('John ""Johnny"" Doe');
    });

    it('should handle commas in values', () => {
      const dataWithCommas = {
        ...mockData,
        rows: [{ name: 'Doe, John', department: 'Engineering', attendance: 95, date: '2024-01-15' }],
      };
      const csv = generateReportCSV(dataWithCommas);

      expect(csv).toContain('"Doe, John"');
    });
  });

  describe('createPrintDocument', () => {
    it('should create valid HTML document', () => {
      const reportHTML = '<div>Test Report</div>';
      const doc = createPrintDocument(reportHTML, 'A4');

      expect(doc).toContain('<!DOCTYPE html>');
      expect(doc).toContain('<html>');
      expect(doc).toContain('<head>');
      expect(doc).toContain('<style>');
      expect(doc).toContain('</head>');
      expect(doc).toContain('<body>');
      expect(doc).toContain('Test Report');
      expect(doc).toContain('</body>');
      expect(doc).toContain('</html>');
    });

    it('should include print styles for A4', () => {
      const doc = createPrintDocument('<div>Test</div>', 'A4');

      expect(doc).toContain('@page');
      expect(doc).toContain('size: A4');
      expect(doc).toContain('margin: 20mm');
    });

    it('should include print styles for Letter', () => {
      const doc = createPrintDocument('<div>Test</div>', 'Letter');

      expect(doc).toContain('size: Letter');
    });

    it('should include page break styles', () => {
      const doc = createPrintDocument('<div>Test</div>', 'A4');

      expect(doc).toContain('page-break-inside: avoid');
      expect(doc).toContain('@media print');
    });
  });

  describe('generateReportFilename', () => {
    it('should generate filename with timestamp for HTML', () => {
      const filename = generateReportFilename('Employee Report', 'html');

      expect(filename).toMatch(/^Employee Report-\d{4}-\d{2}-\d{2}\.html$/);
    });

    it('should generate filename with timestamp for CSV', () => {
      const filename = generateReportFilename('Employee Report', 'csv');

      expect(filename).toMatch(/^Employee Report-\d{4}-\d{2}-\d{2}\.csv$/);
    });

    it('should use current date in filename', () => {
      const today = new Date().toISOString().split('T')[0];
      const filename = generateReportFilename('Test', 'html');

      expect(filename).toContain(today);
    });
  });

  describe('downloadReport', () => {
    it('should create blob with correct MIME type for HTML', () => {
      const blobSpy = vi.spyOn(window, 'Blob' as any);
      downloadReport('<html>Test</html>', 'test.html', 'html');

      expect(blobSpy).toHaveBeenCalledWith(
        expect.any(Array),
        expect.objectContaining({ type: 'text/html;charset=utf-8;' })
      );
    });

    it('should create blob with correct MIME type for CSV', () => {
      const blobSpy = vi.spyOn(window, 'Blob' as any);
      downloadReport('name,age\nJohn,30', 'test.csv', 'csv');

      expect(blobSpy).toHaveBeenCalledWith(
        expect.any(Array),
        expect.objectContaining({ type: 'text/csv;charset=utf-8;' })
      );
    });
  });

  describe('printReport', () => {
    beforeEach(() => {
      vi.spyOn(window, 'open').mockReturnValue({
        document: {
          write: vi.fn(),
          close: vi.fn(),
        },
        print: vi.fn(),
      } as any);
    });

    it('should open print window', () => {
      const openSpy = vi.spyOn(window, 'open');
      printReport('<div>Test</div>', 'A4');

      expect(openSpy).toHaveBeenCalled();
    });

    it('should write HTML to print window', () => {
      const mockWindow = {
        document: {
          write: vi.fn(),
          close: vi.fn(),
        },
        print: vi.fn(),
      };
      vi.spyOn(window, 'open').mockReturnValue(mockWindow as any);

      printReport('<div>Test</div>', 'A4');

      expect(mockWindow.document.write).toHaveBeenCalled();
      expect(mockWindow.document.close).toHaveBeenCalled();
    });
  });
});
