/**
 * Report Generator Utility
 * Formats data into printable reports with metadata
 * 
 * Requirements: 26.5, 26.6, 26.7, 26.8
 */

export interface ReportMetadata {
  title: string;
  description?: string;
  generatedDate: Date;
  generatedBy: string;
  filters?: Record<string, any>;
  pageSize?: 'A4' | 'Letter';
}

export interface ReportData {
  metadata: ReportMetadata;
  columns: ReportColumn[];
  rows: any[];
  summary?: ReportSummary;
}

export interface ReportColumn {
  id: string;
  label: string;
  width?: string;
  align?: 'left' | 'center' | 'right';
  format?: (value: any) => string;
}

export interface ReportSummary {
  label: string;
  value: string | number;
}[]

/**
 * Format metadata for display in report
 */
export const formatReportMetadata = (metadata: ReportMetadata): string => {
  const lines: string[] = [];

  lines.push(`Generated: ${metadata.generatedDate.toLocaleString()}`);
  lines.push(`Generated By: ${metadata.generatedBy}`);

  if (metadata.filters && Object.keys(metadata.filters).length > 0) {
    const filterStr = Object.entries(metadata.filters)
      .map(([key, value]) => {
        if (value === null || value === undefined) return null;
        if (Array.isArray(value)) {
          return `${key}: ${value.join(', ')}`;
        }
        return `${key}: ${value}`;
      })
      .filter(Boolean)
      .join(' | ');

    if (filterStr) {
      lines.push(`Filters: ${filterStr}`);
    }
  }

  return lines.join('\n');
};

/**
 * Format cell value based on column format function
 */
export const formatCellValue = (value: any, column: ReportColumn): string => {
  if (column.format) {
    return column.format(value);
  }

  if (value === null || value === undefined) {
    return '-';
  }

  if (value instanceof Date) {
    return value.toLocaleDateString();
  }

  if (typeof value === 'number') {
    return value.toLocaleString();
  }

  return String(value);
};

/**
 * Generate HTML table from report data
 */
export const generateReportHTML = (data: ReportData): string => {
  const { metadata, columns, rows, summary } = data;

  const headerRow = columns
    .map(
      (col) =>
        `<th style="text-align: ${col.align || 'left'}; width: ${col.width || 'auto'};">${col.label}</th>`
    )
    .join('');

  const bodyRows = rows
    .map(
      (row) =>
        `<tr>${columns
          .map(
            (col) =>
              `<td style="text-align: ${col.align || 'left'};">${formatCellValue(row[col.id], col)}</td>`
          )
          .join('')}</tr>`
    )
    .join('');

  const summaryRows = summary
    ? summary
        .map(
          (item) =>
            `<tr class="summary-row"><td colspan="${columns.length}" style="text-align: right;"><strong>${item.label}:</strong> ${item.value}</td></tr>`
        )
        .join('')
    : '';

  const metadataText = formatReportMetadata(metadata);
  const metadataLines = metadataText.split('\n').map((line) => `<p>${line}</p>`).join('');

  return `
    <div class="report-container">
      <div class="report-header">
        <h1>${metadata.title}</h1>
        ${metadata.description ? `<p class="report-description">${metadata.description}</p>` : ''}
        <div class="report-metadata">
          ${metadataLines}
        </div>
      </div>
      
      <div class="report-content">
        <table class="report-table">
          <thead>
            <tr>${headerRow}</tr>
          </thead>
          <tbody>
            ${bodyRows}
            ${summaryRows}
          </tbody>
        </table>
      </div>
      
      <div class="report-footer">
        <p>Page <span class="page-number"></span> of <span class="page-count"></span></p>
      </div>
    </div>
  `;
};

/**
 * Generate CSV from report data
 */
export const generateReportCSV = (data: ReportData): string => {
  const { metadata, columns, rows, summary } = data;

  const lines: string[] = [];

  // Add metadata as comments
  lines.push(`# ${metadata.title}`);
  if (metadata.description) {
    lines.push(`# ${metadata.description}`);
  }
  lines.push(`# Generated: ${metadata.generatedDate.toLocaleString()}`);
  lines.push(`# Generated By: ${metadata.generatedBy}`);

  if (metadata.filters && Object.keys(metadata.filters).length > 0) {
    const filterStr = Object.entries(metadata.filters)
      .map(([key, value]) => `${key}: ${value}`)
      .join(', ');
    lines.push(`# Filters: ${filterStr}`);
  }

  lines.push(''); // Empty line

  // Add headers
  const headers = columns.map((col) => `"${col.label}"`).join(',');
  lines.push(headers);

  // Add data rows
  rows.forEach((row) => {
    const values = columns
      .map((col) => {
        const value = formatCellValue(row[col.id], col);
        // Escape quotes and wrap in quotes if contains comma or newline
        if (value.includes(',') || value.includes('\n') || value.includes('"')) {
          return `"${value.replace(/"/g, '""')}"`;
        }
        return `"${value}"`;
      })
      .join(',');
    lines.push(values);
  });

  // Add summary
  if (summary) {
    lines.push(''); // Empty line
    summary.forEach((item) => {
      lines.push(`"${item.label}","${item.value}"`);
    });
  }

  return lines.join('\n');
};

/**
 * Create print-friendly HTML document
 */
export const createPrintDocument = (
  reportHTML: string,
  pageSize: 'A4' | 'Letter' = 'A4'
): string => {
  const pageWidth = pageSize === 'A4' ? '210mm' : '8.5in';
  const pageHeight = pageSize === 'A4' ? '297mm' : '11in';

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Report</title>
        <style>
          * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
          }

          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            font-size: 11pt;
            line-height: 1.5;
            color: #333;
          }

          @page {
            size: ${pageSize};
            margin: 20mm;
          }

          @media print {
            body {
              margin: 0;
              padding: 0;
            }

            .report-container {
              page-break-inside: avoid;
            }

            .report-table {
              page-break-inside: avoid;
            }

            tr {
              page-break-inside: avoid;
            }

            .no-print {
              display: none !important;
            }
          }

          .report-container {
            width: 100%;
            margin-bottom: 20mm;
          }

          .report-header {
            margin-bottom: 15mm;
            border-bottom: 2px solid #333;
            padding-bottom: 10mm;
          }

          .report-header h1 {
            font-size: 18pt;
            font-weight: bold;
            margin-bottom: 5mm;
            color: #000;
          }

          .report-description {
            font-size: 11pt;
            color: #666;
            margin-bottom: 5mm;
            font-style: italic;
          }

          .report-metadata {
            font-size: 9pt;
            color: #666;
            margin-top: 5mm;
          }

          .report-metadata p {
            margin: 2mm 0;
          }

          .report-content {
            margin-bottom: 10mm;
          }

          .report-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10mm;
          }

          .report-table thead {
            background-color: #f5f5f5;
            border-bottom: 2px solid #333;
          }

          .report-table th {
            padding: 5mm;
            text-align: left;
            font-weight: bold;
            font-size: 10pt;
            border: 1px solid #ddd;
          }

          .report-table td {
            padding: 4mm;
            border: 1px solid #ddd;
            font-size: 10pt;
          }

          .report-table tbody tr:nth-child(even) {
            background-color: #f9f9f9;
          }

          .report-table tbody tr:hover {
            background-color: #f0f0f0;
          }

          .summary-row {
            background-color: #f5f5f5;
            font-weight: bold;
            border-top: 2px solid #333;
          }

          .report-footer {
            text-align: center;
            font-size: 9pt;
            color: #999;
            margin-top: 10mm;
            padding-top: 5mm;
            border-top: 1px solid #ddd;
          }

          .page-number::before {
            content: counter(page);
          }

          .page-count::before {
            content: counter(pages);
          }

          /* Print controls */
          .print-controls {
            margin-bottom: 10mm;
            padding: 5mm;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
            border-radius: 4px;
          }

          .print-controls button {
            padding: 5mm 10mm;
            margin-right: 5mm;
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 10pt;
          }

          .print-controls button:hover {
            background-color: #0056b3;
          }

          .print-controls button.secondary {
            background-color: #6c757d;
          }

          .print-controls button.secondary:hover {
            background-color: #545b62;
          }
        </style>
      </head>
      <body>
        ${reportHTML}
      </body>
    </html>
  `;
};

/**
 * Download report as file
 */
export const downloadReport = (
  content: string,
  filename: string,
  format: 'html' | 'csv' = 'html'
): void => {
  const mimeType = format === 'html' ? 'text/html;charset=utf-8;' : 'text/csv;charset=utf-8;';
  const blob = new Blob([content], { type: mimeType });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
};

/**
 * Print report directly
 */
export const printReport = (reportHTML: string, pageSize: 'A4' | 'Letter' = 'A4'): void => {
  const printWindow = window.open('', '', 'width=800,height=600');
  if (!printWindow) {
    console.error('Failed to open print window');
    return;
  }

  const fullHTML = createPrintDocument(reportHTML, pageSize);
  printWindow.document.write(fullHTML);
  printWindow.document.close();

  // Wait for content to load before printing
  setTimeout(() => {
    printWindow.print();
  }, 250);
};

/**
 * Generate report filename with timestamp
 */
export const generateReportFilename = (
  prefix: string,
  format: 'html' | 'csv' = 'html'
): string => {
  const timestamp = new Date().toISOString().split('T')[0];
  const ext = format === 'html' ? 'html' : 'csv';
  return `${prefix}-${timestamp}.${ext}`;
};
